<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DebugType>full</DebugType>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="mscorlib" />
    <Reference Include="System.Xaml" />
    <Reference Include="WindowsBase" />
    <Reference Include="PresentationCore" />
    <Reference Include="PresentationFramework" />
    <Reference Include="UIAutomationTypes" />
    <Reference Include="ReachFramework" />
    <Reference Include="System.Printing" />
    <Reference Include="System.ServiceModel" />
    <Reference Include="System.IdentityModel" />
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <SubType>Designer</SubType>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\StoreDatabase\StoreDatabase.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="360.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="362.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="397.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="401.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="404.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Include="image.gif">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
</Project>