<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <TargetFramework>net8.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <ApplicationIcon></ApplicationIcon>
    <AssemblyTitle>Windows7_TaskBar</AssemblyTitle>
    <Company>Microsoft</Company>
    <Product>Windows7_TaskBar</Product>
    <Copyright>Copyright ? Microsoft 2010</Copyright>
  </PropertyGroup>

  <ItemGroup>
    <None Include="readme.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Resource Include="pause.png" />
    <Resource Include="play.png" />
    <Resource Include="pause-big.png" />
    <Resource Include="play-big.png" />
  </ItemGroup>
</Project>